name: FreedomBot
main: com.FoxIshDaBest.FreedomBot.FreedomBot
version: 2.1
author: FoxIshDaBest
depend: [TotalFreedomMod]

commands:
    freedombot:
      description: 'Displays FreedomBot information.'
      usage: /<command>
      
    admintool:
      description: 'Administrator tools.'
      usage: /<command>
      
    opme:
      description: 'Op yourself.'
      usage: /<command>
      
    adminalert:
      description: 'Alert an online administrator.'
      usage: /<command>
      
    verify:
      description: 'Verification system. Password is configurable.'
      usage: /<command>
      
