name: FreedomBot
main: com.mcplugindev.freedombot.FreedomBot
version: 3.0
description: 'FreedomBot is a plugin that will help you with administrating your FreeOp server.'
author: FoxIshDaBest
authors: [DUFC_Liam, Mayoralty, tylerhyperHD, taahanis, CreeperSeth]
depend: [TotalFreedomMod, Aero]

commands:
    freedombot:
      description: 'Displays FreedomBot information.'
      usage: /<command>
      
    opme:
      description: 'Op yourself. You need to remove the TotalFreedomMod''s /opme to use this command.'
      usage: /<command>
      
    adminalert:
      description: 'Alert an online administrator.'
      usage: /<command>
    
    admintool:
        description: 'Cleanup.'
        usage: /<command>
        
    getip:
        description: 'Get a player''s IP adress.'
        usage: /<command>
        
    getgamemode:
        description: 'Get a player''s current gamemode.'
        alias: [ggm]
