name: FreedomBot
main: com.mcplugindev.freedombot.FreedomBot
version: 3.0
description: 'FreedomBot is a plugin that will help you with administrating your FreeOp server.'
author: FoxIshDaBest
authors: [DUFC_Liam, _JustYellow, hypertechHD, rovertdude]
depend: [TotalFreedomMod, Aero]

commands:
    freedombot:
      description: 'Displays FreedomBot information.'
      usage: /<command>
      
    opme:
      description: 'Op yourself.'
      usage: /<command>
      
    adminalert:
      description: 'Alert an online administrator.'
      usage: /<command>
    
    admintool:
        description: 'Cleanup.'
        usage: /<command>
    getip:
        description: 'Get a player''s IP adress.'
        usage: /<command>
    getgamemode:
        description: 'Get a player''s current gamemode.'